// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq-5DeLHxQ',
    appId: '1:854439309076:web:ea5a8369efbb8ba1ed5c01',
    messagingSenderId: '854439309076',
    projectId: 'homedecore-a00b0',
    authDomain: 'homedecore-a00b0.firebaseapp.com',
    storageBucket: 'homedecore-a00b0.appspot.com',
    measurementId: 'G-E197GDH1MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD18zAlObEJ\Q',
    appId: '1:854439309076:android:24e95e98802ca91bed5c01',
    messagingSenderId: '854439309076',
    projectId: 'homedecore-a00b0',
    storageBucket: 'homedecore-a00b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCStgghkJFY-Bw',
    appId: '1:854439309076:ios:7a1fcf307b25c1b9ed5c01',
    messagingSenderId: '854439309076',
    projectId: 'homedecore-a00b0',
    storageBucket: 'homedecore-a00b0.appspot.com',
    iosBundleId: 'com.example.decorHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCStgghkJyYVrO0yZEkgdnGfI4NgIFY-Bw',
    appId: '1:854439309076:ios:7a1fcf307b25c1b9ed5c01',
    messagingSenderId: '854439309076',
    projectId: 'homedecore-a00b0',
    storageBucket: 'homedecore-a00b0.appspot.com',
    iosBundleId: 'com.example.decorHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq-5De7hiVNQ',
    appId: '1:854439309076:web:5ed4968b9e6a0069ed5c01',
    messagingSenderId: '854439309076',
    projectId: 'homedecore-a00b0',
    authDomain: 'homedecore-a00b0.firebaseapp.com',
    storageBucket: 'homedecore-a00b0.appspot.com',
    measurementId: 'G-5VZBP0NYD6',
  );
}
